; Configuration du pool php-fpm pour WordPress
[www]
user = www-data
group = www-data

; Ecoute sur le port TCP (pas de socket Unix) pour que NGINX atteigne WordPress
; via le reseau Docker
listen = 0.0.0.0:9000

; Mode de gestion des processus
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
