FROM debian:bookworm

RUN apt-get update && apt-get install -y \
	nginx \
	openssl \
	&& rm -rf /var/lib/apt/lists/*

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
	-keyout /etc/ssl/private/zakburak.42.fr.key \
	-out /etc/ssl/certs/zakburak.42.fr.crt \
	-subj "/C=FR/ST=IDF/L=Paris/O=42/OU=42/CN=zakburak.42.fr"

COPY conf/nginx.conf /etc/nginx/sites-available/default

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
